### ISSUE TITLE
Error in manifest file

### ISSUE THREAD

**Issue by Gitoffthelawn** [0xfeeddeadbeef/Tabbard#10]
If you go to `about:debugging`, this extension causes the following warning/error:

>  Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

Does this warrant an update?

**Comment by 0xfeeddeadbeef** [comment]
@Gitoffthelawn To avoid managing two separate branches/packages (one for Chrome, another for Firefox), it has a single manifest file. I am fine with that warning. Extension is working regardless. `background.persistent` is intended for Chrome to avoid one extra `chrome.exe` process just for hosting this extension.

**Comment by Gitoffthelawn** [comment]
Thanks for the explanation (and the extension)!

Firefox doesn't currently create an extra `firefox.exe` process just for hosting the extension, does it?

**Comment by 0xfeeddeadbeef** [comment]
@Gitoffthelawn AFAIK, Firefox hosts WebExtensions inside its main browser UI process, and all the web pages in separate content processes. Setting `background.persistent` to `false` has no effect, extension is always loaded in memory.
