### ISSUE TITLE
Change menuitem text when tabs are selected

### ISSUE THREAD

**Issue by Gitoffthelawn** [0xfeeddeadbeef/Tabbard#11]
Hi George,
Would you mind making a small change to the menuitem to be "Copy selected tab URLs" when tabs are selected?
Thanks!

**Comment by 0xfeeddeadbeef** [comment]
#### Chrome

This is a passive extension, it only gets activated when menu item is clicked and does not keep one extra `chrome.exe` process running constantly.

Reacting to tab selection events and modifying a menu item caption dynamically would force this extension to become a persistent one. A simple task of copying URLs is not sufficiently important to warrant so much dedicated resources to this extension. I'd prefer to keep it light and simple.

#### Firefox

Firefox always keeps extensions active. I think this can be done, I'll look into it.

**Comment by 0xfeeddeadbeef** [comment]
@Gitoffthelawn I've pushed a new version to Firefox.  Chrome edition remains unchanged.

**Comment by Gitoffthelawn** [comment]
Thank you so much!
