### ISSUE TITLE
Disable copying of system tabs

### ISSUE THREAD

**Issue by smaragdus** [0xfeeddeadbeef/Tabbard#12]
I would appreciate if there is an option system tabs:

- about:addons
- about:blank
- about:config
- moz-extension:

etc, not to be copied. A new check box in extension options might be added:

- Do not copy system tabs

which, when checked, will skip copying such system tabs.

I suppose this option will not be hard to be implemented.

**Comment by smaragdus** [comment]
In my first post I added system tabs to be skipped only for Firefox. Now I add list of tabs to be skipped in Chromium:

- chrome://bookmarks/
- chrome://extensions/
- chrome://flags/
- chrome://history/
- chrome://settings/

I may have missed some other system tabs.

**Comment by Gitoffthelawn** [comment]
This is a great idea.

In Firefox, it would probably be best to have an option to just exclude:

- about:*

and *possibly*

- moz-extension:*

But not exclude:

- chrome:*
- resource:*

In Firefox, if you have `chrome` or `resource` tabs open, it's likely you are developing code and want them copied too.

If you want to get fancy, you could have individual checkboxes for each type... then it wouldn't need to be different across browsers.

**Comment by 0xfeeddeadbeef** [comment]
I'll also include `brave:*` into this list. Sadly, there is no `isSystemTab` flag on [Tab](https://developer.chrome.com/extensions/tabs#type-Tab) object.

**Comment by Gitoffthelawn** [comment]
I know uBlock Origin uses specifiers like `about-scheme`.  See https://github.com/gorhill/uBlock/blob/1.25.2/src/js/background.js#L114

I only mention it if it happens to help you.  Otherwise, I think it's better to just use specifiers like `about:*`.

**Comment by Gitoffthelawn** [comment]
Any thoughts on implementing this?  It would be a significant improvement to a great extension! :)

**Comment by 0xfeeddeadbeef** [comment]
Sorry. [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/) will kill this extension. Continuing its support is pointless. Closing the issue.
