### ISSUE TITLE
Option to not copy duplicate tabs

### ISSUE THREAD

**Issue by Gitoffthelawn** [0xfeeddeadbeef/Tabbard#13]
Following the recent request by @smaragdus, I'll propose another feature request.

I would appreciate if there is an option that duplicate tabs (identical URL's) not to be copied. A new check box in extension options might be added:

    Do not copy duplicate tabs

which, when checked, will skip copying such duplicate tabs.

I suppose this option will not be hard to be implemented.

Thank you to @smaragdus for creating a template and saving me some typing. :)

**Comment by smaragdus** [comment]
@Gitoffthelawn 

In my [first post](https://github.com/0xfeeddeadbeef/Tabbard/issues/12#issue-581494907) I added a list of system tabs only for Firefox, In my [second post](https://github.com/0xfeeddeadbeef/Tabbard/issues/12#issuecomment-599219747) I added a list of system tabs for Chromium as well. I might have missed some other system tabs.

**Comment by Gitoffthelawn** [comment]
@smaragdus wrote:

> @Gitoffthelawn
> 
> In my [first post](https://github.com/0xfeeddeadbeef/Tabbard/issues/12#issue-581494907) I added a list of system tabs only for Firefox, In my [second post](https://github.com/0xfeeddeadbeef/Tabbard/issues/12#issuecomment-599219747) I added a list of system tabs for Chromium as well. I might have missed some other system tabs.

Great!  I'll take a look.  Did you mean to post the above comment here or over there?  BTW, I'm referring to all tabs with duplicate URL's in this issue (not just system ones).

**Comment by smaragdus** [comment]
@Gitoffthelawn 

> Did you mean to post the above comment here or over there?

I meant posting my comment here because you mentioned me here.

By the way- do you know whether the original developer (@0xfeeddeadbeef) is accepting pull requests?

**Comment by Gitoffthelawn** [comment]
@smaragdus 

> By the way- do you know whether the original developer (@0xfeeddeadbeef) is accepting pull requests?

I believe so.  I recall submitting a pull request for this project a while back, and they accepted it.

**Comment by smaragdus** [comment]
@Gitoffthelawn 

> I believe so. I recall submitting a pull request for this project a while back, and they accepted it.

Good news. If you have time to enhance this extension I may suggest few other features in the future.

**Comment by Gitoffthelawn** [comment]
> > I believe so. I recall submitting a pull request for this project a while back, and they accepted it.
> 
> Good news. If you have time to enhance this extension I may suggest few other features in the future.

I'm sorry, I probably won't have time to work on it in the near future (if there is a near future...).

But AFAIK, suggestions are always welcome! :)

**Comment by smaragdus** [comment]
> I'm sorry, I probably won't have time to work on it in the near future (if there is a near future...).

There will always be a future but perhaps not for us.

Take care and good luck!

**Comment by 0xfeeddeadbeef** [comment]
Should not be too hard. There is a very useful [Set object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) in JavaScript.

**Comment by Gitoffthelawn** [comment]
Great!  Thanks!

**Comment by 0xfeeddeadbeef** [comment]
Sorry. [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/) will kill this extension. Continuing its support is pointless. Closing the issue.
