### ISSUE TITLE
Failing to copy sleeping/disabled/suspended tabs

### ISSUE THREAD

**Issue by Gitoffthelawn** [0xfeeddeadbeef/Tabbard#14]
Tabbard isn't copying sleeping/disabled/suspended tabs.

I will really appreciate it if it would do this!

Thanks so much.

**Comment by 0xfeeddeadbeef** [comment]
Sorry. [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/) will kill this extension. Continuing its support is pointless. Closing the issue.
