### ISSUE TITLE
Allow copying the title & URL of only the current tab

### ISSUE THREAD

**Issue by Gitoffthelawn** [0xfeeddeadbeef/Tabbard#15]
Thank you for the great extension.

The one feature I find missing is the ability to copy the title & URL of *only* the current tab.  Would it be possible to add this feature?

The implementation could be as simple as adding an additional (optional) menuitem for just the current tab, but other implementations are possible as well.

Thank you!  👍🏾

**Comment by 0xfeeddeadbeef** [comment]
Sorry. [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/) will kill this extension. Continuing its support is pointless. Closing the issue.
