### ISSUE TITLE
Add option to remove context menu items

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [0xfeeddeadbeef/Tabbard#6]
One might not like cluttered context menus.

**Comment by Gitoffthelawn** [comment]
It would be great to be able to specify which menus on which to add items.  For example, I regularly us the one on the tab context menu, but never on the page (content) context menu.

**Comment by 0xfeeddeadbeef** [comment]
Sorry. [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/) will kill this extension. Continuing its support is pointless. Closing the issue.
