### ISSUE TITLE
Copy only current window links

### ISSUE THREAD

**Issue by mistic100** [0xfeeddeadbeef/Tabbard#7]
Using Firefox 65

When using the plugin, the clipboard contains URLs of all tabs across all opened windows, it would be usefull to only copy the current window tabs.

**Comment by 0xfeeddeadbeef** [comment]
@mistic100  Done. Added as an option 'Copy only currently focused window tabs':
![Tabbard-Titles](https://user-images.githubusercontent.com/732366/54073323-3d77b780-429f-11e9-862d-5de71f5d9ed8.png)

**Comment by mistic100** [comment]
thank you
