### ISSUE TITLE
Copy only URL

### ISSUE THREAD

**Issue by mistic100** [0xfeeddeadbeef/Tabbard#8]
Using Firefox 65

I would like to be able to copy only the URL of the tabs, without the name.

**Comment by 0xfeeddeadbeef** [comment]
Tabbard already has the described feature, see Options page for 'Do not copy site titles':
![Tabbard-Titles](https://user-images.githubusercontent.com/732366/54073280-b591ad80-429e-11e9-9446-419333f249ea.png)
