### ISSUE TITLE
Copy only selected tabs

### ISSUE THREAD

**Issue by Gitoffthelawn** [0xfeeddeadbeef/Tabbard#9]
Users can now select tabs in Firefox.  When more than one tab is selected, how about changing the menuitem to "Copy selected tabs URLs" and just copy those?

**Comment by 0xfeeddeadbeef** [comment]
@Gitoffthelawn Done. Tested in both Chrome and Firefox.

**Comment by Gitoffthelawn** [comment]
Thank you so much!
